# Generated by Django 3.1.7 on 2021-03-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210316_0702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'slug')},
        ),
    ]
